name: mern-app

services:
  mongo: 
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

  
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mern-app
    depends_on: 
      - mongo

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    environment:
    - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-app
    command: npm run dev -- --host
    depends_on:
      - api
  
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mern-app
    depends_on:
      - web
      - api

volumes:
  mongo_data:
  caddy_config:
  caddy_data:

networks:
  mern-app:
    driver: bridge
