name: Node.js CI

on:
  push:
    paths: 
      - 'week04/github-actions-cicd-docker/backend**'
    branches: [ main ]
  pull_request:
    paths: 
        - 'week04/github-actions-cicd-docker/backend**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./week04/github-actions-cicd-docker/backend

      - name: Run test
        run: npm test
        working-directory: ./week04/github-actions-cicd-docker/backend
