name: Node.js CI

on:
  push:
    paths: 
      - 'github-actions-cicd-docker/**'
    branches: [ main ]
  pull_request:
    paths: 
        - 'github-actions-cicd-docker/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set working directory
        working-directory: ./week04/github-actions-cicd-docker
      - run: npm install
      - run: npm test
